### ISSUE TITLE
Bloomfilter Server pass to use json codification instead Gob one

### ISSUE THREAD

**Issue by froilson** [krakend/bloomfilter#17]
**Is your feature request related to a problem? Please describe.**
Bloomfilter server is encoded using gob as the net/rpc package is using it, so to revoke a token we only can use a client in Golang.

**Describe the solution you'd like**
Change the encoding to json with net/rpc/jsonrpc.

**Describe alternatives you've considered**
How can I generate a Java client to call bloomfilter server instead.

**Comment by alombarte** [comment]
It is not viable to send the bloomfilter using JSON given the size it holds
