### ISSUE TITLE
What happens on a restart? 

### ISSUE THREAD

**Issue by ankit16-19** [krakend/bloomfilter#20]
What happens when a krakend pod with `auth/revoker` setup. Gets restarted.
To my understanding as bloomfilter is in memory only. All data will get purged.

How do i ensure that on rollout/restart, blocked token doesn't become valid again?

**Comment by alombarte** [comment]
You must emulate the [Enterprise edition's behavior](https://www.krakend.io/docs/enterprise/authentication/revoke-server/) and push the bloomfilter again to all instances when they start. This component only takes care of the bloomfilter, and not any of the orchestration part.
